package pojo;
// Generated May 16, 2014 8:22:14 AM by Hibernate Tools 3.6.0



/**
 * EventToLocation generated by hbm2java
 */
public class EventToLocation  implements java.io.Serializable {


     private Integer id;
     private Event event;
     private Location location;
     private int toOrder;

    public EventToLocation() {
    }

    public EventToLocation(Event event, Location location, int toOrder) {
       this.event = event;
       this.location = location;
       this.toOrder = toOrder;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public int getToOrder() {
        return this.toOrder;
    }
    
    public void setToOrder(int toOrder) {
        this.toOrder = toOrder;
    }




}


