package pojo;
// Generated May 20, 2014 9:21:31 AM by Hibernate Tools 3.6.0



/**
 * ExistInId generated by hbm2java
 */
public class ExistInId  implements java.io.Serializable {


     private int userId;
     private int circleId;

    public ExistInId() {
    }

    public ExistInId(int userId, int circleId) {
       this.userId = userId;
       this.circleId = circleId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getCircleId() {
        return this.circleId;
    }
    
    public void setCircleId(int circleId) {
        this.circleId = circleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExistInId) ) return false;
		 ExistInId castOther = ( ExistInId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getCircleId()==castOther.getCircleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getCircleId();
         return result;
   }   


}


