package pojo;
// Generated May 16, 2014 8:22:14 AM by Hibernate Tools 3.6.0



/**
 * JoinEventId generated by hbm2java
 */
public class JoinEventId  implements java.io.Serializable {


     private int eventId;
     private int userId;

    public JoinEventId() {
    }

    public JoinEventId(int eventId, int userId) {
       this.eventId = eventId;
       this.userId = userId;
    }
   
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JoinEventId) ) return false;
		 JoinEventId castOther = ( JoinEventId ) other; 
         
		 return (this.getEventId()==castOther.getEventId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEventId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


