package pojo;
// Generated May 20, 2014 5:05:58 AM by Hibernate Tools 3.6.0



/**
 * JoinEvent generated by hbm2java
 */
public class JoinEvent  implements java.io.Serializable {


     private JoinEventId id;
     private User user;
     private Event event;
     private UserStatue userStatue;

    public JoinEvent() {
    }

    public JoinEvent(JoinEventId id, User user, Event event, UserStatue userStatue) {
       this.id = id;
       this.user = user;
       this.event = event;
       this.userStatue = userStatue;
    }
   
    public JoinEventId getId() {
        return this.id;
    }
    
    public void setId(JoinEventId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public UserStatue getUserStatue() {
        return this.userStatue;
    }
    
    public void setUserStatue(UserStatue userStatue) {
        this.userStatue = userStatue;
    }




}


