package pojo;
// Generated May 16, 2014 8:22:14 AM by Hibernate Tools 3.6.0



/**
 * Phone generated by hbm2java
 */
public class Phone  implements java.io.Serializable {


     private String phone;
     private User user;

    public Phone() {
    }

    public Phone(String phone, User user) {
       this.phone = phone;
       this.user = user;
    }
   
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


