package pojo;
// Generated May 16, 2014 8:22:14 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String username;
     private String password;
     private String gender;
     private Date dateOfBirth;
     private String pushNotificationId;
     private String rank;
     private String userImage;
     private String email;
     private String facebookKey;
     private String phone;
     private Set joinEvents = new HashSet(0);
     private Set events = new HashSet(0);
     private Set phones = new HashSet(0);
     private Set notifications = new HashSet(0);
     private Set circles = new HashSet(0);
     private Set comments = new HashSet(0);
     private Set existIns = new HashSet(0);

    public User() {
    }

	
    public User(String name, String username, String password, String phone) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.phone = phone;
    }
    public User(String name, String username, String password, String gender, Date dateOfBirth, String pushNotificationId, String rank, String userImage, String email, String facebookKey, String phone, Set joinEvents, Set events, Set phones, Set notifications, Set circles, Set comments, Set existIns) {
       this.name = name;
       this.username = username;
       this.password = password;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.pushNotificationId = pushNotificationId;
       this.rank = rank;
       this.userImage = userImage;
       this.email = email;
       this.facebookKey = facebookKey;
       this.phone = phone;
       this.joinEvents = joinEvents;
       this.events = events;
       this.phones = phones;
       this.notifications = notifications;
       this.circles = circles;
       this.comments = comments;
       this.existIns = existIns;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getPushNotificationId() {
        return this.pushNotificationId;
    }
    
    public void setPushNotificationId(String pushNotificationId) {
        this.pushNotificationId = pushNotificationId;
    }
    public String getRank() {
        return this.rank;
    }
    
    public void setRank(String rank) {
        this.rank = rank;
    }
    public String getUserImage() {
        return this.userImage;
    }
    
    public void setUserImage(String userImage) {
        this.userImage = userImage;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFacebookKey() {
        return this.facebookKey;
    }
    
    public void setFacebookKey(String facebookKey) {
        this.facebookKey = facebookKey;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Set getJoinEvents() {
        return this.joinEvents;
    }
    
    public void setJoinEvents(Set joinEvents) {
        this.joinEvents = joinEvents;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }
    public Set getPhones() {
        return this.phones;
    }
    
    public void setPhones(Set phones) {
        this.phones = phones;
    }
    public Set getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(Set notifications) {
        this.notifications = notifications;
    }
    public Set getCircles() {
        return this.circles;
    }
    
    public void setCircles(Set circles) {
        this.circles = circles;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getExistIns() {
        return this.existIns;
    }
    
    public void setExistIns(Set existIns) {
        this.existIns = existIns;
    }




}


